/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, EndUser } from "@prisma/client";

export class EndUserServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.EndUserCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.EndUserCountArgs>
  ): Promise<number> {
    return this.prisma.endUser.count(args);
  }

  async endUsers<T extends Prisma.EndUserFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.EndUserFindManyArgs>
  ): Promise<EndUser[]> {
    return this.prisma.endUser.findMany(args);
  }
  async endUser<T extends Prisma.EndUserFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EndUserFindUniqueArgs>
  ): Promise<EndUser | null> {
    return this.prisma.endUser.findUnique(args);
  }
  async createEndUser<T extends Prisma.EndUserCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EndUserCreateArgs>
  ): Promise<EndUser> {
    return this.prisma.endUser.create<T>(args);
  }
  async updateEndUser<T extends Prisma.EndUserUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EndUserUpdateArgs>
  ): Promise<EndUser> {
    return this.prisma.endUser.update<T>(args);
  }
  async deleteEndUser<T extends Prisma.EndUserDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.EndUserDeleteArgs>
  ): Promise<EndUser> {
    return this.prisma.endUser.delete(args);
  }
}
