/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EndUser } from "./EndUser";
import { EndUserCountArgs } from "./EndUserCountArgs";
import { EndUserFindManyArgs } from "./EndUserFindManyArgs";
import { EndUserFindUniqueArgs } from "./EndUserFindUniqueArgs";
import { DeleteEndUserArgs } from "./DeleteEndUserArgs";
import { EndUserService } from "../endUser.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EndUser)
export class EndUserResolverBase {
  constructor(
    protected readonly service: EndUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EndUser",
    action: "read",
    possession: "any",
  })
  async _endUsersMeta(
    @graphql.Args() args: EndUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EndUser])
  @nestAccessControl.UseRoles({
    resource: "EndUser",
    action: "read",
    possession: "any",
  })
  async endUsers(
    @graphql.Args() args: EndUserFindManyArgs
  ): Promise<EndUser[]> {
    return this.service.endUsers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EndUser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EndUser",
    action: "read",
    possession: "own",
  })
  async endUser(
    @graphql.Args() args: EndUserFindUniqueArgs
  ): Promise<EndUser | null> {
    const result = await this.service.endUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EndUser)
  @nestAccessControl.UseRoles({
    resource: "EndUser",
    action: "delete",
    possession: "any",
  })
  async deleteEndUser(
    @graphql.Args() args: DeleteEndUserArgs
  ): Promise<EndUser | null> {
    try {
      return await this.service.deleteEndUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
